
import { RuneData } from './types';

export const RUNES: RuneData[] = [
  {
    id: 1,
    symbol: 'ᚠ',
    name: 'Fehu',
    animal: '松鼠',
    image: '/cards/001松鼠.png',
    meaning: '財富、生成',
    upright: '財務或能量的新增、創業、資源到來。',
    reversed: '消耗、錯置資源、需重新評估價值觀。',
    message: '提醒你察覺何處有能量流動，並用明智的手段守護或分享它。',
    practice: '握符想像暖流進入掌心，冥想「我配得豐盛」，或用於吸引機會的小儀式。',
    category: '物質與成長'
  },
  {
    id: 2,
    symbol: 'ᚢ',
    name: 'Uruz',
    animal: '公牛',
    image: '/cards/002公牛.png',
    meaning: '原始力量、健康',
    upright: '恢復、勇氣、自我強化。',
    reversed: '衝動、健康忽視或能量枯竭。',
    message: '呼喚你回到本能，面對需要力量的挑戰。',
    practice: '做根基的呼吸與身體練習；在開始艱難任務前喚醒它。',
    category: '力量與本能'
  },
  {
    id: 3,
    symbol: 'ᚦ',
    name: 'Thurisaz',
    animal: '狼',
    image: '/cards/003狼.png',
    meaning: '力量之門、挑戰',
    upright: '保護、必要的衝突、突破障礙。',
    reversed: '被攻擊、過度防衛或誤用力量。',
    message: '有一個關鍵的界限或試煉，你需選擇面對或智慧迴避。',
    practice: '在邊界問題上使用，或以它做防禦的護符。',
    category: '力量與邊界'
  },
  {
    id: 4,
    symbol: 'ᚨ',
    name: 'Ansuz',
    animal: '烏鴉',
    image: '/cards/004烏鴉.png',
    meaning: '啟示、言語、神諭',
    upright: '清晰的訊息、教授、靈感到來。',
    reversed: '誤解、謊言或訊息受阻。',
    message: '留心你收到或需要傳達的話——它們可能是關鍵。',
    practice: '寫下直覺閃現的句子，或在占卜後尋求進一步啟示。',
    category: '靈性與溝通'
  },
  {
    id: 5,
    symbol: 'ᚱ',
    name: 'Raidho',
    animal: '鯨魚',
    image: '/cards/005鯨魚.png',
    meaning: '路徑、旅程、節奏',
    upright: '動態的變化、順序、正當的行動。',
    reversed: '延誤、錯過的節拍或方向不明。',
    message: '走在正確的節奏上；若感到停滯，調整步伐而非強推。',
    practice: '使用它來為計畫排列步驟或助於旅途決策。',
    category: '旅途與秩序'
  },
  {
    id: 6,
    symbol: 'ᚲ',
    name: 'Kenaz',
    animal: '貓頭鷹',
    image: '/cards/006貓頭鷹.png',
    meaning: '火、洞見、創造',
    upright: '靈感燃起、學習、技藝精進。',
    reversed: '創意阻塞、過度曝光或誤用技術。',
    message: '新的點子或技術可以被點燃，投身於工藝或學習。',
    practice: '冥想點燃的火焰，讓它帶走陰霾並喚來洞見。',
    category: '知識與轉化'
  },
  {
    id: 7,
    symbol: 'ᚷ',
    name: 'Gebo',
    animal: '天鵝',
    image: '/cards/007白天鵝.png',
    meaning: '交換、禮物、盟約',
    upright: '互惠關係、禮物或達成協議。',
    reversed: '不平等的給予、期待回報的操縱。',
    message: '關係需要回應與平衡；一份禮物或協議正在形成。',
    practice: '書寫感謝或交換的意圖；用作修補關係的象徵。',
    category: '平衡與盟約'
  },
  {
    id: 8,
    symbol: 'ᚹ',
    name: 'Wunjo',
    animal: '蜂鳥',
     image: '/cards/008蜂鳥.png',
    meaning: '喜悅、和諧、社群',
    upright: '快樂、和諧、目標達成。',
    reversed: '表面歡愉掩蓋內在不滿。',
    message: '你可慶祝，但也要誠實面對真正的心聲。',
    practice: '想像和聲的笑聲，讓它療癒受傷的角落。',
    category: '喜悅與和諧'
  },
  {
    id: 9,
    symbol: 'ᚺ',
    name: 'Hagalaz',
    animal: '蠍子',
     image: '/cards/009蠍子.png',
    meaning: '破壞與重整、自然力量',
    upright: '不可抗外力帶來的淨化與改變。',
    reversed: '延長的混亂或拒絕改變。',
    message: '某個結構需要瓦解才能重建；接受必要的破壞。',
    practice: '在面對大變局時與它共舞，讓舊事凋零為新生留下空間。',
    category: '命運與重整'
  },
  {
    id: 10,
    symbol: 'ᚾ',
    name: 'Nauthiz',
    animal: '黑熊',
     image: '/cards/010黑熊.png',
    meaning: '需求、限制、耐心',
    upright: '學會耐心、找出真實的需要。',
    reversed: '恐懼驅動的強求或無止境的欲望。',
    message: '當下的阻礙是提醒你調整資源與欲望。',
    practice: '深吸，辨識「必要」與「想要」的差別，練習節制。',
    category: '限制與耐力'
  },
  {
    id: 11,
    symbol: 'ᛁ',
    name: 'Isa',
    animal: '蝙蝠',
    image: '/cards/011蝙蝠.png',
    meaning: '凝滯、專注、潛伏之力',
    upright: '停下來療癒、反思與保持冷靜。',
    reversed: '僵化、恐懼導致停滯不前。',
    message: '此刻可能需要等待或保持低調，別強行推動。',
    practice: '觀察內心的結冰處，讓時間和冷靜軟化它。',
    category: '靜止與保護'
  },
  {
    id: 12,
    symbol: 'ᛃ',
    name: 'Jera',
    animal: '蜜蜂',
    image: '/cards/012蜜蜂.png',
    meaning: '循環、收成、自然時序',
    upright: '一個周期完成，收穫來臨。',
    reversed: '期望太急或收成被延遲。',
    message: '信任時序：付出會在對的季節回報。',
    practice: '記錄工作與成果的循環，培養耐心與感恩。',
    category: '時間與回報'
  },
  {
    id: 13,
    symbol: 'ᛇ',
    name: 'Eihwaz',
    animal: '黑貓',
    image: '/cards/013黑貓.png',
    meaning: '靈性守護、變形之樹',
    upright: '堅韌、守護、靈性轉化。',
    reversed: '抗拒轉化或被動等待。',
    message: '你正處於靈性考驗或需依靠內在守護。',
    practice: '想像一棵深根的樹支撐你，尋找內在的穩定。',
    category: '守護與轉化'
  },
  {
    id: 14,
    symbol: 'ᛈ',
    name: 'Perthro',
    animal: '蛇',
    image: '/cards/014蛇.png',
    meaning: '神秘、命運之杯、潛藏的機會',
    upright: '未知的機會、命運的玩笑或直覺的揭示。',
    reversed: '危險的賭注或過度依賴偶然。',
    message: '有事尚未揭露，或你需接受無法完全掌控的元素。',
    practice: '接納不確定，使用抽籤或直覺遊戲來探索可能。',
    category: '秘密與命運'
  },
  {
    id: 15,
    symbol: 'ᛉ',
    name: 'Algiz',
    animal: '羚羊',
    image: '/cards/015羚羊.png',
    meaning: '保護、靈感的觸角',
    upright: '保護到位、靈感的守護與直覺的警示。',
    reversed: '保護薄弱或誤判威脅。',
    message: '你受守護，或需要建立更清晰的界限。',
    practice: '在需要時用作護符或作為建立界限的象徵冥想。',
    category: '連結與守護'
  },
  {
    id: 16,
    symbol: 'ᛋ',
    name: 'Sowilo',
    animal: '翠鳥',
    image: '/cards/016翠鳥.png',
    meaning: '太陽的勝利、導向力',
    upright: '能量充沛、目標達成、啟明。',
    reversed: '自大、迷失於耀眼或短暫的勝利。',
    message: '光明在前；追求正道會帶來成功，但保持謙遜。',
    practice: '在低潮時呼喚它作為重建自信的火苗。',
    category: '勝利與光明'
  },
  {
    id: 17,
    symbol: 'ᛏ',
    name: 'Tiwaz',
    animal: '禿鷹',
    image: '/cards/017禿鷹.png', 
    meaning: '勝利、正義、犧牲的勇氣',
    upright: '正義、公正決策、堅定的行動。',
    reversed: '不公平、為勝利而犧牲倫理。',
    message: '你面臨道德的選擇；正直比短暫勝利更長久。',
    practice: '在困難決策時，用它來檢視你的動機與結果。',
    category: '榮耀與正義'
  },
  {
    id: 18,
    symbol: 'ᛒ',
    name: 'Berkano',
    animal: '兔子',
    image: '/cards/018兔子.png', 
    meaning: '新生、孕育、家庭',
    upright: '新計畫、孕育階段、療癒的家庭能量。',
    reversed: '停滯的成長或家庭衝突。',
    message: '一段溫柔的成長正在醞釀；給它時間與空間。',
    practice: '用於育成計畫、身心療癒或和解的儀式。',
    category: '母性與成長'
  },
  {
    id: 19,
    symbol: 'ᛖ',
    name: 'Ehwaz',
    animal: '白馬',
    image: '/cards/019白馬.png', 
    meaning: '伙伴、移動、信任的駿馬',
    upright: '合作順利、流暢的移動、關係中的信任。',
    reversed: '背叛、錯誤的夥伴或停滯的旅程。',
    message: '尋找可依賴的夥伴或檢視現有關係的互信。',
    practice: '在人際或事業合作上把它當作促進信任的象徵。',
    category: '合作與互信'
  },
  {
    id: 20,
    symbol: 'ᛗ',
    name: 'Mannaz',
    animal: '貓鼬',
    image: '/cards/020貓鼬.png', 
    meaning: '人性、社會結構、自我認知',
    upright: '自我覺察、社群支援與智慧合作。',
    reversed: '自我中心、被群體壓抑或身份危機。',
    message: '你需要反思自己的社會角色或尋求支持。',
    practice: '自省與群體工作並重，書寫你的角色與貢獻。',
    category: '自我與社群'
  },
  {
    id: 21,
    symbol: 'ᛚ',
    name: 'Laguz',
    animal: '海馬',
    image: '/cards/021海馬.png',
    meaning: '水、直覺、流動的智慧',
    upright: '直覺強烈、情感流通、療癒的深度。',
    reversed: '情緒淹沒或直覺被忽略。',
    message: '信任內在感受；它會為你開啟隱秘的路徑。',
    practice: '做夢日記、流動的冥想或進行水之儀式以清晰直覺。',
    category: '直覺與夢境'
  },
  {
    id: 22,
    symbol: 'ᛜ',
    name: 'Ingwaz',
    animal: '獅子',
    image: '/cards/022獅子.png', 
    meaning: '內在的種子、安定、完成',
    upright: '內在整合、計畫準備完畢，期待萌發。',
    reversed: '停留在潛能無法落地或過度閉鎖。',
    message: '準備收束或播下會在未來生根的種子。',
    practice: '在計畫結束或孕育階段使用，確認下一步的準備。',
    category: '豐饒與整合'
  },
  {
    id: 23,
    symbol: 'ᛞ',
    name: 'Dagaz',
    animal: '蝴蝶',
    image: '/cards/023蝴蝶.png',
    meaning: '曙光、轉化、突破',
    upright: '徹底的轉機、明晰與新的開始。',
    reversed: '過度劇變 or 誤解轉機的本質。',
    message: '你即將跨過關鍵門檻，曙光正在逼近。',
    practice: '黎明冥想，迎接新的視角與行動。',
    category: '覺醒與突破'
  },
  {
    id: 24,
    symbol: 'ᛟ',
    name: 'Othala',
    animal: '寄居蟹',
    image: '/cards/024寄居蟹.png',
    meaning: '遺產、根源、屬地與傳承',
    upright: '找到根基、繼承與保護傳統資產。',
    reversed: '對過去的執著或不正當的佔有。',
    message: '你需連接根源或整理與遺產有關的關係。',
    practice: '探索家族故事、療癒傳承或以它光膜守護居所。',
    category: '傳承與家園'
  }
];
